export default {
    name:"comment",
    type:"document",
    title:"Comment",
    fields:[
        {
            name:"string",
            type:"string",
        },
        {
            name:"Approved",
            type:"approved",
            type:"boolean",
            description:"Comments wont show on the site without approval"
        },
        {
            name:"email",
            type:"string",
        },
        {
            name:"comment",
            type:"text",
        },
        {
            name:"post",
            type:"reference",
            to:[{type:"post"}]
        }
    ]
}