import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import styles from '../styles/Home.module.css'
import {sanityClient, urlFor} from '../lib/sanity';
import { Post } from '../typings'
import Link from 'next/link'
// import { groq } from "next-sanity";


interface Props{
  posts:Post[];
}

const Home = ({posts}:Props) => {
  return (
    <div className="max-w-7xl mx-auto">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>

      <div className="flex justify-between items-center bg-yellow-400 border-y border-black py-10 md:py-0">
        <div className="px-10 space-y-5"> 
          <h1 className="text-6xl max-w-xl font-serif">
            <span className="underline decoration-black decoration-4">Medium</span>&nbsp;
            is a place to write ,read and connect
          </h1>
          <h2>
            It&apos;s easy and free to post your thinking on any topic and connect with millions of readers
          </h2>
        </div>

        <div>

        </div>
        <img 
          className="hidden md:inline-flex h-32 lg:h-full"
          src="https://accountabilitylab.org/wp-content/uploads/2020/03/Medium-logo.png" alt=""/>
      </div>

      {/* posts  */} 
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3 md:gap-6 p-2 md:p-6">
        {
          posts.map((post)=>(
            <Link key={post._id} href={`/posts/${post.slug.current}`}>
              <div className='cursor-pointer group rounded-lg border overflow-hidden'>
                <img src={urlFor(post.mainImage).url()!} alt="/" className="h-60 w-full object-cover group-hover:scale-105 duration-200 transition-transform ease-in-out" />
                <div className="flex justify-between p-5 bg-white">
                  <div>
                    <p className="text-lg font-bold">{post.title}</p>
                    <p className="text-xs">{post.description} by {post.author.name}</p>
                  </div>
                  <img className='h-12 w-12 rounded-full' src={urlFor(post.author.image).url()!} alt=""/>
                </div>
              </div>
            </Link>
          ))
        }
      </div>

    </div>
  )
}
export default Home

export const getServerSideProps = async() =>{
  const query = `
    *[_type == "post"]{
      _id,
      title,
      mainImage,
      description,
      slug,
      author->{
      name,
      image
    }
  }
  `;
  const posts = await sanityClient.fetch(query);
  console.log(posts);
  return {
    props:{
      posts
    }
  }

}
